# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: bash

services:
  - docker

before_install:
  - sudo pip install --upgrade pip
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_USERNAME" --password-stdin

install:
    cd docker;
    docker build --no-cache -t somrc/consultr:latest . || exit 1;
    docker push somrc/consultr:latest || exit 1;
    aws sqs send-message --queue-url 'https://queue.amazonaws.com/474683445819/dcos-refresh' --message-body 'somrc/consultr' || exit 1;

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - vpnagraj@virginia.edu
